// Products
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const SEARCH_INPUT = 'SEARCH_INPUT'

//Orders
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const RECEIVE_ORDER = 'RECEIVE_ORDER';

//Categories
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const CATEGORIES_SELECTED = 'CATEGORIES_SELECTED'

//Users
export const RECEIVE_USER = 'RECEIVE_USER';



